# Generated by Django 4.1.3 on 2022-11-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('envs', models.JSONField()),
                ('command', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('R', 'Running'), ('Finished', 'F')], max_length=100)),
                ('envs', models.JSONField()),
                ('command', models.CharField(max_length=200)),
                ('app_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.app')),
            ],
        ),
    ]
